[package]
name = "auralion"
version = "0.0.1-alpha0"
edition = "2021"

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
random-string = "1.0.0"
reqwest = { version = "0.11.13", features = ["blocking"] }
serde = { version = "1.0.149", features = ["derive"]}
serde_json = "1.0.89"
toml = "0.5.9"
